# Generated by Django 3.1.13 on 2021-08-16 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 16, 11, 11, 7, 743900)),
        ),
    ]
